"""initial schema

Revision ID: 342cbfe4030f
Revises: 
Create Date: 2026-05-15 13:51:20.998197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342cbfe4030f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_nombre'), 'marcas', ['nombre'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'GESTOR', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('subcategorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marca_id', 'nombre', name='uq_subcategoria_marca_nombre')
    )
    op.create_index(op.f('ix_subcategorias_marca_id'), 'subcategorias', ['marca_id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_individual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_caja', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_descuento_individual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_descuento_caja', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fortaleza', sa.Enum('SUAVE', 'MEDIO', 'FUERTE', 'SUAVE_MEDIO', 'MEDIO_FUERTE', name='fortaleza'), nullable=True),
    sa.Column('tiempo_fumado_min', sa.Integer(), nullable=True),
    sa.Column('tiempo_fumado_max', sa.Integer(), nullable=True),
    sa.Column('cepo', sa.Integer(), nullable=True),
    sa.Column('largo_mm', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('existencia', sa.Boolean(), nullable=False),
    sa.Column('imagen', sa.String(length=500), nullable=True),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('subcategoria_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 100', name='ck_producto_rating_range'),
    sa.CheckConstraint('tiempo_fumado_min IS NULL OR tiempo_fumado_max IS NULL OR tiempo_fumado_min <= tiempo_fumado_max', name='ck_producto_tiempo_range'),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategoria_id'], ['subcategorias.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_marca_id'), 'productos', ['marca_id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_index(op.f('ix_productos_subcategoria_id'), 'productos', ['subcategoria_id'], unique=False)
    op.create_table('valoraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('valoracion', sa.Text(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_valoracion_rating_range'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valoraciones_email'), 'valoraciones', ['email'], unique=False)
    op.create_index(op.f('ix_valoraciones_producto_id'), 'valoraciones', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valoraciones_producto_id'), table_name='valoraciones')
    op.drop_index(op.f('ix_valoraciones_email'), table_name='valoraciones')
    op.drop_table('valoraciones')
    op.drop_index(op.f('ix_productos_subcategoria_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_marca_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_subcategorias_marca_id'), table_name='subcategorias')
    op.drop_table('subcategorias')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_marcas_nombre'), table_name='marcas')
    op.drop_table('marcas')
    # ### end Alembic commands ###
