"""subcategoria_id nullable in productos

Revision ID: 98c7ce7413dc
Revises: 6a5249bc8972
Create Date: 2026-05-19 08:08:29.244260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c7ce7413dc'
down_revision: Union[str, None] = '6a5249bc8972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productos', 'subcategoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
