"""add vitola to productos

Revision ID: c70eb5a2a893
Revises: 342cbfe4030f
Create Date: 2026-05-18 14:05:12.849745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70eb5a2a893'
down_revision: Union[str, None] = '342cbfe4030f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('vitola', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'vitola')
    # ### end Alembic commands ###
